# Generated by Django 5.2.1 on 2026-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_ads', models.ManyToManyField(blank=True, related_name='device_groups', to='ads.ad')),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='devices.device')),
            ],
        ),
    ]
