# Generated by Django 5.2.1 on 2026-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Kill Switch',
                'verbose_name_plural': 'Kill Switch',
            },
        ),
    ]
