# Generated by Django 5.2.1 on 2026-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Site logo displayed in sidebar and login page.', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (recommended 32x32 or 64x64 PNG/ICO).', null=True, upload_to='branding/')),
                ('site_name', models.CharField(default='DigiPlay', help_text='Site name shown in sidebar and page titles.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
